package com.tw.mapper;

import com.tw.model.Address;
import com.tw.model.AddressCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @SelectProvider(type=AddressSqlProvider.class, method="countByExample")
    long countByExample(AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AddressSqlProvider.class, method="deleteByExample")
    int deleteByExample(AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_address",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_address (id, user_id, ",
        "user_name, tel_number, ",
        "postal_Code, national_Code, ",
        "province_Name, city_Name, ",
        "county_Name, detail_Info, ",
        "is_default)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{telNumber,jdbcType=VARCHAR}, ",
        "#{postalCode,jdbcType=VARCHAR}, #{nationalCode,jdbcType=VARCHAR}, ",
        "#{provinceName,jdbcType=VARCHAR}, #{cityName,jdbcType=VARCHAR}, ",
        "#{countyName,jdbcType=VARCHAR}, #{detailInfo,jdbcType=VARCHAR}, ",
        "#{isDefault,jdbcType=INTEGER})"
    })
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @InsertProvider(type=AddressSqlProvider.class, method="insertSelective")
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @SelectProvider(type=AddressSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel_number", property="telNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="postal_Code", property="postalCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="national_Code", property="nationalCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_Name", property="provinceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_Name", property="cityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="county_Name", property="countyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail_Info", property="detailInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_default", property="isDefault", jdbcType=JdbcType.INTEGER)
    })
    List<Address> selectByExampleWithRowbounds(AddressCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @SelectProvider(type=AddressSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel_number", property="telNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="postal_Code", property="postalCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="national_Code", property="nationalCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_Name", property="provinceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_Name", property="cityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="county_Name", property="countyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail_Info", property="detailInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_default", property="isDefault", jdbcType=JdbcType.INTEGER)
    })
    List<Address> selectByExample(AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user_id, user_name, tel_number, postal_Code, national_Code, province_Name, ",
        "city_Name, county_Name, detail_Info, is_default",
        "from twshop_address",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel_number", property="telNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="postal_Code", property="postalCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="national_Code", property="nationalCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_Name", property="provinceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_Name", property="cityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="county_Name", property="countyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail_Info", property="detailInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_default", property="isDefault", jdbcType=JdbcType.INTEGER)
    })
    Address selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AddressSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Address record, @Param("example") AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AddressSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Address record, @Param("example") AddressCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AddressSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_address",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "tel_number = #{telNumber,jdbcType=VARCHAR},",
          "postal_Code = #{postalCode,jdbcType=VARCHAR},",
          "national_Code = #{nationalCode,jdbcType=VARCHAR},",
          "province_Name = #{provinceName,jdbcType=VARCHAR},",
          "city_Name = #{cityName,jdbcType=VARCHAR},",
          "county_Name = #{countyName,jdbcType=VARCHAR},",
          "detail_Info = #{detailInfo,jdbcType=VARCHAR},",
          "is_default = #{isDefault,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Address record);
}