package com.tw.mapper;

import com.tw.model.Address;
import com.tw.model.AddressCriteria.Criteria;
import com.tw.model.AddressCriteria.Criterion;
import com.tw.model.AddressCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class AddressSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    public String countByExample(AddressCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("twshop_address");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    public String deleteByExample(AddressCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("twshop_address");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    public String insertSelective(Address record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("twshop_address");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.VALUES("user_name", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getTelNumber() != null) {
            sql.VALUES("tel_number", "#{telNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPostalCode() != null) {
            sql.VALUES("postal_Code", "#{postalCode,jdbcType=VARCHAR}");
        }
        
        if (record.getNationalCode() != null) {
            sql.VALUES("national_Code", "#{nationalCode,jdbcType=VARCHAR}");
        }
        
        if (record.getProvinceName() != null) {
            sql.VALUES("province_Name", "#{provinceName,jdbcType=VARCHAR}");
        }
        
        if (record.getCityName() != null) {
            sql.VALUES("city_Name", "#{cityName,jdbcType=VARCHAR}");
        }
        
        if (record.getCountyName() != null) {
            sql.VALUES("county_Name", "#{countyName,jdbcType=VARCHAR}");
        }
        
        if (record.getDetailInfo() != null) {
            sql.VALUES("detail_Info", "#{detailInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDefault() != null) {
            sql.VALUES("is_default", "#{isDefault,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    public String selectByExample(AddressCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("user_id");
        sql.SELECT("user_name");
        sql.SELECT("tel_number");
        sql.SELECT("postal_Code");
        sql.SELECT("national_Code");
        sql.SELECT("province_Name");
        sql.SELECT("city_Name");
        sql.SELECT("county_Name");
        sql.SELECT("detail_Info");
        sql.SELECT("is_default");
        sql.FROM("twshop_address");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Address record = (Address) parameter.get("record");
        AddressCriteria example = (AddressCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("twshop_address");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getTelNumber() != null) {
            sql.SET("tel_number = #{record.telNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPostalCode() != null) {
            sql.SET("postal_Code = #{record.postalCode,jdbcType=VARCHAR}");
        }
        
        if (record.getNationalCode() != null) {
            sql.SET("national_Code = #{record.nationalCode,jdbcType=VARCHAR}");
        }
        
        if (record.getProvinceName() != null) {
            sql.SET("province_Name = #{record.provinceName,jdbcType=VARCHAR}");
        }
        
        if (record.getCityName() != null) {
            sql.SET("city_Name = #{record.cityName,jdbcType=VARCHAR}");
        }
        
        if (record.getCountyName() != null) {
            sql.SET("county_Name = #{record.countyName,jdbcType=VARCHAR}");
        }
        
        if (record.getDetailInfo() != null) {
            sql.SET("detail_Info = #{record.detailInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDefault() != null) {
            sql.SET("is_default = #{record.isDefault,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_address");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
        sql.SET("tel_number = #{record.telNumber,jdbcType=VARCHAR}");
        sql.SET("postal_Code = #{record.postalCode,jdbcType=VARCHAR}");
        sql.SET("national_Code = #{record.nationalCode,jdbcType=VARCHAR}");
        sql.SET("province_Name = #{record.provinceName,jdbcType=VARCHAR}");
        sql.SET("city_Name = #{record.cityName,jdbcType=VARCHAR}");
        sql.SET("county_Name = #{record.countyName,jdbcType=VARCHAR}");
        sql.SET("detail_Info = #{record.detailInfo,jdbcType=VARCHAR}");
        sql.SET("is_default = #{record.isDefault,jdbcType=INTEGER}");
        
        AddressCriteria example = (AddressCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Address record) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_address");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUserName() != null) {
            sql.SET("user_name = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getTelNumber() != null) {
            sql.SET("tel_number = #{telNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getPostalCode() != null) {
            sql.SET("postal_Code = #{postalCode,jdbcType=VARCHAR}");
        }
        
        if (record.getNationalCode() != null) {
            sql.SET("national_Code = #{nationalCode,jdbcType=VARCHAR}");
        }
        
        if (record.getProvinceName() != null) {
            sql.SET("province_Name = #{provinceName,jdbcType=VARCHAR}");
        }
        
        if (record.getCityName() != null) {
            sql.SET("city_Name = #{cityName,jdbcType=VARCHAR}");
        }
        
        if (record.getCountyName() != null) {
            sql.SET("county_Name = #{countyName,jdbcType=VARCHAR}");
        }
        
        if (record.getDetailInfo() != null) {
            sql.SET("detail_Info = #{detailInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDefault() != null) {
            sql.SET("is_default = #{isDefault,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_address
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, AddressCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}