package com.tw.mapper;

import com.tw.model.Ad;
import com.tw.model.AdCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface AdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @SelectProvider(type=AdSqlProvider.class, method="countByExample")
    long countByExample(AdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AdSqlProvider.class, method="deleteByExample")
    int deleteByExample(AdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_ad",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_ad (id, ad_position_id, ",
        "media_type, name, ",
        "link, content, end_time, ",
        "enabled, image_url)",
        "values (#{id,jdbcType=SMALLINT}, #{adPositionId,jdbcType=SMALLINT}, ",
        "#{mediaType,jdbcType=TINYINT}, #{name,jdbcType=VARCHAR}, ",
        "#{link,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{enabled,jdbcType=TINYINT}, #{imageUrl,jdbcType=LONGVARCHAR})"
    })
    int insert(Ad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @InsertProvider(type=AdSqlProvider.class, method="insertSelective")
    int insertSelective(Ad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @SelectProvider(type=AdSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="ad_position_id", property="adPositionId", jdbcType=JdbcType.SMALLINT),
        @Result(column="media_type", property="mediaType", jdbcType=JdbcType.TINYINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="link", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.TINYINT),
        @Result(column="image_url", property="imageUrl", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Ad> selectByExampleWithBLOBsWithRowbounds(AdCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @SelectProvider(type=AdSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="ad_position_id", property="adPositionId", jdbcType=JdbcType.SMALLINT),
        @Result(column="media_type", property="mediaType", jdbcType=JdbcType.TINYINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="link", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.TINYINT),
        @Result(column="image_url", property="imageUrl", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Ad> selectByExampleWithBLOBs(AdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @SelectProvider(type=AdSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="ad_position_id", property="adPositionId", jdbcType=JdbcType.SMALLINT),
        @Result(column="media_type", property="mediaType", jdbcType=JdbcType.TINYINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="link", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.TINYINT)
    })
    List<Ad> selectByExampleWithRowbounds(AdCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @SelectProvider(type=AdSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="ad_position_id", property="adPositionId", jdbcType=JdbcType.SMALLINT),
        @Result(column="media_type", property="mediaType", jdbcType=JdbcType.TINYINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="link", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.TINYINT)
    })
    List<Ad> selectByExample(AdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, ad_position_id, media_type, name, link, content, end_time, enabled, image_url",
        "from twshop_ad",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.SMALLINT, id=true),
        @Result(column="ad_position_id", property="adPositionId", jdbcType=JdbcType.SMALLINT),
        @Result(column="media_type", property="mediaType", jdbcType=JdbcType.TINYINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="link", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.TINYINT),
        @Result(column="image_url", property="imageUrl", jdbcType=JdbcType.LONGVARCHAR)
    })
    Ad selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AdSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Ad record, @Param("example") AdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AdSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") Ad record, @Param("example") AdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AdSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Ad record, @Param("example") AdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AdSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Ad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_ad",
        "set ad_position_id = #{adPositionId,jdbcType=SMALLINT},",
          "media_type = #{mediaType,jdbcType=TINYINT},",
          "name = #{name,jdbcType=VARCHAR},",
          "link = #{link,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "enabled = #{enabled,jdbcType=TINYINT},",
          "image_url = #{imageUrl,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKeyWithBLOBs(Ad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_ad
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_ad",
        "set ad_position_id = #{adPositionId,jdbcType=SMALLINT},",
          "media_type = #{mediaType,jdbcType=TINYINT},",
          "name = #{name,jdbcType=VARCHAR},",
          "link = #{link,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "enabled = #{enabled,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=SMALLINT}"
    })
    int updateByPrimaryKey(Ad record);
}