package com.tw.mapper;

import com.tw.model.Attribute;
import com.tw.model.AttributeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface AttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeSqlProvider.class, method="countByExample")
    long countByExample(AttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AttributeSqlProvider.class, method="deleteByExample")
    int deleteByExample(AttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_attribute",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_attribute (id, attribute_category_id, ",
        "name, input_type, ",
        "sort_order, value)",
        "values (#{id,jdbcType=INTEGER}, #{attributeCategoryId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{inputType,jdbcType=INTEGER}, ",
        "#{sortOrder,jdbcType=INTEGER}, #{value,jdbcType=LONGVARCHAR})"
    })
    int insert(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @InsertProvider(type=AttributeSqlProvider.class, method="insertSelective")
    int insertSelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="attribute_category_id", property="attributeCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="input_type", property="inputType", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="value", property="value", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Attribute> selectByExampleWithBLOBsWithRowbounds(AttributeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="attribute_category_id", property="attributeCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="input_type", property="inputType", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="value", property="value", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<Attribute> selectByExampleWithBLOBs(AttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="attribute_category_id", property="attributeCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="input_type", property="inputType", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<Attribute> selectByExampleWithRowbounds(AttributeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="attribute_category_id", property="attributeCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="input_type", property="inputType", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER)
    })
    List<Attribute> selectByExample(AttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, attribute_category_id, name, input_type, sort_order, value",
        "from twshop_attribute",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="attribute_category_id", property="attributeCategoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="input_type", property="inputType", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="value", property="value", jdbcType=JdbcType.LONGVARCHAR)
    })
    Attribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttributeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Attribute record, @Param("example") AttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttributeSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") Attribute record, @Param("example") AttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttributeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Attribute record, @Param("example") AttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttributeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_attribute",
        "set attribute_category_id = #{attributeCategoryId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "input_type = #{inputType,jdbcType=INTEGER},",
          "sort_order = #{sortOrder,jdbcType=INTEGER},",
          "value = #{value,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_attribute",
        "set attribute_category_id = #{attributeCategoryId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "input_type = #{inputType,jdbcType=INTEGER},",
          "sort_order = #{sortOrder,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Attribute record);
}