package com.tw.mapper;

import com.tw.model.AttributeCategory;
import com.tw.model.AttributeCategoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface AttributeCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeCategorySqlProvider.class, method="countByExample")
    long countByExample(AttributeCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AttributeCategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(AttributeCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_attribute_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_attribute_category (id, name, ",
        "enabled)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{enabled,jdbcType=BIT})"
    })
    int insert(AttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @InsertProvider(type=AttributeCategorySqlProvider.class, method="insertSelective")
    int insertSelective(AttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.BIT)
    })
    List<AttributeCategory> selectByExampleWithRowbounds(AttributeCategoryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=AttributeCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.BIT)
    })
    List<AttributeCategory> selectByExample(AttributeCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, enabled",
        "from twshop_attribute_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.BIT)
    })
    AttributeCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttributeCategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AttributeCategory record, @Param("example") AttributeCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttributeCategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AttributeCategory record, @Param("example") AttributeCategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AttributeCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AttributeCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_attribute_category
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_attribute_category",
        "set name = #{name,jdbcType=VARCHAR},",
          "enabled = #{enabled,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AttributeCategory record);
}