package com.tw.mapper;

import com.tw.model.Brand;
import com.tw.model.BrandCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @SelectProvider(type=BrandSqlProvider.class, method="countByExample")
    long countByExample(BrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @DeleteProvider(type=BrandSqlProvider.class, method="deleteByExample")
    int deleteByExample(BrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_brand",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_brand (id, name, ",
        "list_pic_url, simple_desc, ",
        "pic_url, sort_order, ",
        "is_show, floor_price, ",
        "app_list_pic_url, is_new, ",
        "new_pic_url, new_sort_order, ",
        "brand_Type, addr, ",
        "user_id, max_Discount, ",
        "sum_Discount, logo)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{listPicUrl,jdbcType=VARCHAR}, #{simpleDesc,jdbcType=VARCHAR}, ",
        "#{picUrl,jdbcType=VARCHAR}, #{sortOrder,jdbcType=TINYINT}, ",
        "#{isShow,jdbcType=CHAR}, #{floorPrice,jdbcType=DECIMAL}, ",
        "#{appListPicUrl,jdbcType=VARCHAR}, #{isNew,jdbcType=CHAR}, ",
        "#{newPicUrl,jdbcType=VARCHAR}, #{newSortOrder,jdbcType=TINYINT}, ",
        "#{brandType,jdbcType=INTEGER}, #{addr,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=INTEGER}, #{maxDiscount,jdbcType=INTEGER}, ",
        "#{sumDiscount,jdbcType=DECIMAL}, #{logo,jdbcType=VARCHAR})"
    })
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @InsertProvider(type=BrandSqlProvider.class, method="insertSelective")
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @SelectProvider(type=BrandSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="list_pic_url", property="listPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_desc", property="simpleDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="pic_url", property="picUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.TINYINT),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.CHAR),
        @Result(column="floor_price", property="floorPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="app_list_pic_url", property="appListPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_new", property="isNew", jdbcType=JdbcType.CHAR),
        @Result(column="new_pic_url", property="newPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="new_sort_order", property="newSortOrder", jdbcType=JdbcType.TINYINT),
        @Result(column="brand_Type", property="brandType", jdbcType=JdbcType.INTEGER),
        @Result(column="addr", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="max_Discount", property="maxDiscount", jdbcType=JdbcType.INTEGER),
        @Result(column="sum_Discount", property="sumDiscount", jdbcType=JdbcType.DECIMAL),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR)
    })
    List<Brand> selectByExampleWithRowbounds(BrandCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @SelectProvider(type=BrandSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="list_pic_url", property="listPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_desc", property="simpleDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="pic_url", property="picUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.TINYINT),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.CHAR),
        @Result(column="floor_price", property="floorPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="app_list_pic_url", property="appListPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_new", property="isNew", jdbcType=JdbcType.CHAR),
        @Result(column="new_pic_url", property="newPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="new_sort_order", property="newSortOrder", jdbcType=JdbcType.TINYINT),
        @Result(column="brand_Type", property="brandType", jdbcType=JdbcType.INTEGER),
        @Result(column="addr", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="max_Discount", property="maxDiscount", jdbcType=JdbcType.INTEGER),
        @Result(column="sum_Discount", property="sumDiscount", jdbcType=JdbcType.DECIMAL),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR)
    })
    List<Brand> selectByExample(BrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, list_pic_url, simple_desc, pic_url, sort_order, is_show, floor_price, ",
        "app_list_pic_url, is_new, new_pic_url, new_sort_order, brand_Type, addr, user_id, ",
        "max_Discount, sum_Discount, logo",
        "from twshop_brand",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="list_pic_url", property="listPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_desc", property="simpleDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="pic_url", property="picUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.TINYINT),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.CHAR),
        @Result(column="floor_price", property="floorPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="app_list_pic_url", property="appListPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_new", property="isNew", jdbcType=JdbcType.CHAR),
        @Result(column="new_pic_url", property="newPicUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="new_sort_order", property="newSortOrder", jdbcType=JdbcType.TINYINT),
        @Result(column="brand_Type", property="brandType", jdbcType=JdbcType.INTEGER),
        @Result(column="addr", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="max_Discount", property="maxDiscount", jdbcType=JdbcType.INTEGER),
        @Result(column="sum_Discount", property="sumDiscount", jdbcType=JdbcType.DECIMAL),
        @Result(column="logo", property="logo", jdbcType=JdbcType.VARCHAR)
    })
    Brand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BrandSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BrandSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Brand record, @Param("example") BrandCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BrandSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_brand
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_brand",
        "set name = #{name,jdbcType=VARCHAR},",
          "list_pic_url = #{listPicUrl,jdbcType=VARCHAR},",
          "simple_desc = #{simpleDesc,jdbcType=VARCHAR},",
          "pic_url = #{picUrl,jdbcType=VARCHAR},",
          "sort_order = #{sortOrder,jdbcType=TINYINT},",
          "is_show = #{isShow,jdbcType=CHAR},",
          "floor_price = #{floorPrice,jdbcType=DECIMAL},",
          "app_list_pic_url = #{appListPicUrl,jdbcType=VARCHAR},",
          "is_new = #{isNew,jdbcType=CHAR},",
          "new_pic_url = #{newPicUrl,jdbcType=VARCHAR},",
          "new_sort_order = #{newSortOrder,jdbcType=TINYINT},",
          "brand_Type = #{brandType,jdbcType=INTEGER},",
          "addr = #{addr,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "max_Discount = #{maxDiscount,jdbcType=INTEGER},",
          "sum_Discount = #{sumDiscount,jdbcType=DECIMAL},",
          "logo = #{logo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Brand record);
}