package com.tw.mapper;

import com.tw.model.Category;
import com.tw.model.CategoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=CategorySqlProvider.class, method="countByExample")
    long countByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_category (id, name, ",
        "keywords, front_desc, ",
        "parent_id, sort_order, ",
        "show_index, is_show, banner_url, ",
        "icon_url, img_url, ",
        "wap_banner_url, level, ",
        "type, front_name)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{keywords,jdbcType=VARCHAR}, #{frontDesc,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=INTEGER}, #{sortOrder,jdbcType=BIT}, ",
        "#{showIndex,jdbcType=BIT}, #{isShow,jdbcType=BIT}, #{bannerUrl,jdbcType=VARCHAR}, ",
        "#{iconUrl,jdbcType=VARCHAR}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{wapBannerUrl,jdbcType=VARCHAR}, #{level,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{frontName,jdbcType=VARCHAR})"
    })
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @InsertProvider(type=CategorySqlProvider.class, method="insertSelective")
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=CategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="keywords", property="keywords", jdbcType=JdbcType.VARCHAR),
        @Result(column="front_desc", property="frontDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.BIT),
        @Result(column="show_index", property="showIndex", jdbcType=JdbcType.BIT),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.BIT),
        @Result(column="banner_url", property="bannerUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon_url", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="wap_banner_url", property="wapBannerUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="front_name", property="frontName", jdbcType=JdbcType.VARCHAR)
    })
    List<Category> selectByExampleWithRowbounds(CategoryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @SelectProvider(type=CategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="keywords", property="keywords", jdbcType=JdbcType.VARCHAR),
        @Result(column="front_desc", property="frontDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.BIT),
        @Result(column="show_index", property="showIndex", jdbcType=JdbcType.BIT),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.BIT),
        @Result(column="banner_url", property="bannerUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon_url", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="wap_banner_url", property="wapBannerUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="front_name", property="frontName", jdbcType=JdbcType.VARCHAR)
    })
    List<Category> selectByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, keywords, front_desc, parent_id, sort_order, show_index, is_show, ",
        "banner_url, icon_url, img_url, wap_banner_url, level, type, front_name",
        "from twshop_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="keywords", property="keywords", jdbcType=JdbcType.VARCHAR),
        @Result(column="front_desc", property="frontDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.BIT),
        @Result(column="show_index", property="showIndex", jdbcType=JdbcType.BIT),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.BIT),
        @Result(column="banner_url", property="bannerUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon_url", property="iconUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="wap_banner_url", property="wapBannerUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="front_name", property="frontName", jdbcType=JdbcType.VARCHAR)
    })
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Category record, @Param("example") CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_category
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_category",
        "set name = #{name,jdbcType=VARCHAR},",
          "keywords = #{keywords,jdbcType=VARCHAR},",
          "front_desc = #{frontDesc,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=INTEGER},",
          "sort_order = #{sortOrder,jdbcType=BIT},",
          "show_index = #{showIndex,jdbcType=BIT},",
          "is_show = #{isShow,jdbcType=BIT},",
          "banner_url = #{bannerUrl,jdbcType=VARCHAR},",
          "icon_url = #{iconUrl,jdbcType=VARCHAR},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "wap_banner_url = #{wapBannerUrl,jdbcType=VARCHAR},",
          "level = #{level,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "front_name = #{frontName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Category record);
}