package com.tw.mapper;

import com.tw.model.GoodsAttribute;
import com.tw.model.GoodsAttributeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsAttributeSqlProvider.class, method="countByExample")
    long countByExample(GoodsAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @DeleteProvider(type=GoodsAttributeSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_goods_attribute",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_goods_attribute (id, goods_id, ",
        "attribute_id, value)",
        "values (#{id,jdbcType=INTEGER}, #{goodsId,jdbcType=VARCHAR}, ",
        "#{attributeId,jdbcType=INTEGER}, #{value,jdbcType=VARCHAR})"
    })
    int insert(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @InsertProvider(type=GoodsAttributeSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsAttributeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribute_id", property="attributeId", jdbcType=JdbcType.INTEGER),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsAttribute> selectByExampleWithRowbounds(GoodsAttributeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsAttributeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribute_id", property="attributeId", jdbcType=JdbcType.INTEGER),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsAttribute> selectByExample(GoodsAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, goods_id, attribute_id, value",
        "from twshop_goods_attribute",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribute_id", property="attributeId", jdbcType=JdbcType.INTEGER),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR)
    })
    GoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsAttributeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsAttribute record, @Param("example") GoodsAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsAttributeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsAttribute record, @Param("example") GoodsAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsAttributeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_attribute
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_goods_attribute",
        "set goods_id = #{goodsId,jdbcType=VARCHAR},",
          "attribute_id = #{attributeId,jdbcType=INTEGER},",
          "value = #{value,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GoodsAttribute record);
}