package com.tw.mapper;

import com.tw.model.GoodsSkuKey;
import com.tw.model.GoodsSkuKeyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GoodsSkuKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuKeySqlProvider.class, method="countByExample")
    long countByExample(GoodsSkuKeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @DeleteProvider(type=GoodsSkuKeySqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsSkuKeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_goods_sku_key",
        "where key_id = #{keyId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_goods_sku_key (key_id, key_name, ",
        "status, create_time, ",
        "goods_id, sort)",
        "values (#{keyId,jdbcType=VARCHAR}, #{keyName,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{goodsId,jdbcType=VARCHAR}, #{sort,jdbcType=INTEGER})"
    })
    int insert(GoodsSkuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @InsertProvider(type=GoodsSkuKeySqlProvider.class, method="insertSelective")
    int insertSelective(GoodsSkuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuKeySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="key_name", property="keyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER)
    })
    List<GoodsSkuKey> selectByExampleWithRowbounds(GoodsSkuKeyCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuKeySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="key_name", property="keyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER)
    })
    List<GoodsSkuKey> selectByExample(GoodsSkuKeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "key_id, key_name, status, create_time, goods_id, sort",
        "from twshop_goods_sku_key",
        "where key_id = #{keyId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="key_name", property="keyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.INTEGER)
    })
    GoodsSkuKey selectByPrimaryKey(String keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuKeySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsSkuKey record, @Param("example") GoodsSkuKeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuKeySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsSkuKey record, @Param("example") GoodsSkuKeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuKeySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsSkuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_key
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_goods_sku_key",
        "set key_name = #{keyName,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "goods_id = #{goodsId,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=INTEGER}",
        "where key_id = #{keyId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GoodsSkuKey record);
}