package com.tw.mapper;

import com.tw.model.GoodsGallery;
import com.tw.model.GoodsGalleryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GoodsGalleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsGallerySqlProvider.class, method="countByExample")
    long countByExample(GoodsGalleryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @DeleteProvider(type=GoodsGallerySqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsGalleryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_goods_gallery",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_goods_gallery (id, goods_id, ",
        "img_desc, sort_order, ",
        "img_url)",
        "values (#{id,jdbcType=INTEGER}, #{goodsId,jdbcType=VARCHAR}, ",
        "#{imgDesc,jdbcType=VARCHAR}, #{sortOrder,jdbcType=INTEGER}, ",
        "#{imgUrl,jdbcType=VARCHAR})"
    })
    int insert(GoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @InsertProvider(type=GoodsGallerySqlProvider.class, method="insertSelective")
    int insertSelective(GoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsGallerySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_desc", property="imgDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsGallery> selectByExampleWithRowbounds(GoodsGalleryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsGallerySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_desc", property="imgDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsGallery> selectByExample(GoodsGalleryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, goods_id, img_desc, sort_order, img_url",
        "from twshop_goods_gallery",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_desc", property="imgDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort_order", property="sortOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="img_url", property="imgUrl", jdbcType=JdbcType.VARCHAR)
    })
    GoodsGallery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsGallerySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsGallery record, @Param("example") GoodsGalleryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsGallerySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsGallery record, @Param("example") GoodsGalleryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsGallerySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_gallery
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_goods_gallery",
        "set goods_id = #{goodsId,jdbcType=VARCHAR},",
          "img_desc = #{imgDesc,jdbcType=VARCHAR},",
          "sort_order = #{sortOrder,jdbcType=INTEGER},",
          "img_url = #{imgUrl,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GoodsGallery record);
}