package com.tw.mapper;

import com.tw.model.GoodsSkuCompose;
import com.tw.model.GoodsSkuComposeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GoodsSkuComposeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuComposeSqlProvider.class, method="countByExample")
    long countByExample(GoodsSkuComposeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @DeleteProvider(type=GoodsSkuComposeSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsSkuComposeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_goods_sku_compose",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_goods_sku_compose (id, sku_id, ",
        "goods_id, sku_key_id, ",
        "sku_key_name, sku_value_id, ",
        "sku_value_name)",
        "values (#{id,jdbcType=VARCHAR}, #{skuId,jdbcType=VARCHAR}, ",
        "#{goodsId,jdbcType=VARCHAR}, #{skuKeyId,jdbcType=VARCHAR}, ",
        "#{skuKeyName,jdbcType=VARCHAR}, #{skuValueId,jdbcType=VARCHAR}, ",
        "#{skuValueName,jdbcType=VARCHAR})"
    })
    int insert(GoodsSkuCompose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @InsertProvider(type=GoodsSkuComposeSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsSkuCompose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuComposeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_key_id", property="skuKeyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_key_name", property="skuKeyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_value_id", property="skuValueId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_value_name", property="skuValueName", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsSkuCompose> selectByExampleWithRowbounds(GoodsSkuComposeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuComposeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_key_id", property="skuKeyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_key_name", property="skuKeyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_value_id", property="skuValueId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_value_name", property="skuValueName", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsSkuCompose> selectByExample(GoodsSkuComposeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, sku_id, goods_id, sku_key_id, sku_key_name, sku_value_id, sku_value_name",
        "from twshop_goods_sku_compose",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_key_id", property="skuKeyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_key_name", property="skuKeyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_value_id", property="skuValueId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_value_name", property="skuValueName", jdbcType=JdbcType.VARCHAR)
    })
    GoodsSkuCompose selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuComposeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsSkuCompose record, @Param("example") GoodsSkuComposeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuComposeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsSkuCompose record, @Param("example") GoodsSkuComposeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuComposeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsSkuCompose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_goods_sku_compose",
        "set sku_id = #{skuId,jdbcType=VARCHAR},",
          "goods_id = #{goodsId,jdbcType=VARCHAR},",
          "sku_key_id = #{skuKeyId,jdbcType=VARCHAR},",
          "sku_key_name = #{skuKeyName,jdbcType=VARCHAR},",
          "sku_value_id = #{skuValueId,jdbcType=VARCHAR},",
          "sku_value_name = #{skuValueName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GoodsSkuCompose record);
}