package com.tw.mapper;

import com.tw.model.GoodsSkuValue;
import com.tw.model.GoodsSkuValueCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GoodsSkuValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuValueSqlProvider.class, method="countByExample")
    long countByExample(GoodsSkuValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @DeleteProvider(type=GoodsSkuValueSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsSkuValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_goods_sku_value",
        "where value_id = #{valueId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String valueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_goods_sku_value (value_id, key_id, ",
        "value_name, status, ",
        "create_time)",
        "values (#{valueId,jdbcType=VARCHAR}, #{keyId,jdbcType=VARCHAR}, ",
        "#{valueName,jdbcType=VARCHAR}, #{status,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(GoodsSkuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @InsertProvider(type=GoodsSkuValueSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsSkuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuValueSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="value_id", property="valueId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="value_name", property="valueName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<GoodsSkuValue> selectByExampleWithRowbounds(GoodsSkuValueCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuValueSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="value_id", property="valueId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="value_name", property="valueName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<GoodsSkuValue> selectByExample(GoodsSkuValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "value_id, key_id, value_name, status, create_time",
        "from twshop_goods_sku_value",
        "where value_id = #{valueId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="value_id", property="valueId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="key_id", property="keyId", jdbcType=JdbcType.VARCHAR),
        @Result(column="value_name", property="valueName", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    GoodsSkuValue selectByPrimaryKey(String valueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuValueSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsSkuValue record, @Param("example") GoodsSkuValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuValueSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsSkuValue record, @Param("example") GoodsSkuValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuValueSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsSkuValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_value
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_goods_sku_value",
        "set key_id = #{keyId,jdbcType=VARCHAR},",
          "value_name = #{valueName,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where value_id = #{valueId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GoodsSkuValue record);
}