package com.tw.mapper;

import com.tw.model.GoodsSkuCompose;
import com.tw.model.GoodsSkuComposeCriteria.Criteria;
import com.tw.model.GoodsSkuComposeCriteria.Criterion;
import com.tw.model.GoodsSkuComposeCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class GoodsSkuComposeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    public String countByExample(GoodsSkuComposeCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("twshop_goods_sku_compose");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    public String deleteByExample(GoodsSkuComposeCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("twshop_goods_sku_compose");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    public String insertSelective(GoodsSkuCompose record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("twshop_goods_sku_compose");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuId() != null) {
            sql.VALUES("sku_id", "#{skuId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            sql.VALUES("goods_id", "#{goodsId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuKeyId() != null) {
            sql.VALUES("sku_key_id", "#{skuKeyId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuKeyName() != null) {
            sql.VALUES("sku_key_name", "#{skuKeyName,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueId() != null) {
            sql.VALUES("sku_value_id", "#{skuValueId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueName() != null) {
            sql.VALUES("sku_value_name", "#{skuValueName,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    public String selectByExample(GoodsSkuComposeCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("sku_id");
        sql.SELECT("goods_id");
        sql.SELECT("sku_key_id");
        sql.SELECT("sku_key_name");
        sql.SELECT("sku_value_id");
        sql.SELECT("sku_value_name");
        sql.FROM("twshop_goods_sku_compose");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        GoodsSkuCompose record = (GoodsSkuCompose) parameter.get("record");
        GoodsSkuComposeCriteria example = (GoodsSkuComposeCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("twshop_goods_sku_compose");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuId() != null) {
            sql.SET("sku_id = #{record.skuId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            sql.SET("goods_id = #{record.goodsId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuKeyId() != null) {
            sql.SET("sku_key_id = #{record.skuKeyId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuKeyName() != null) {
            sql.SET("sku_key_name = #{record.skuKeyName,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueId() != null) {
            sql.SET("sku_value_id = #{record.skuValueId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueName() != null) {
            sql.SET("sku_value_name = #{record.skuValueName,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_goods_sku_compose");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("sku_id = #{record.skuId,jdbcType=VARCHAR}");
        sql.SET("goods_id = #{record.goodsId,jdbcType=VARCHAR}");
        sql.SET("sku_key_id = #{record.skuKeyId,jdbcType=VARCHAR}");
        sql.SET("sku_key_name = #{record.skuKeyName,jdbcType=VARCHAR}");
        sql.SET("sku_value_id = #{record.skuValueId,jdbcType=VARCHAR}");
        sql.SET("sku_value_name = #{record.skuValueName,jdbcType=VARCHAR}");
        
        GoodsSkuComposeCriteria example = (GoodsSkuComposeCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(GoodsSkuCompose record) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_goods_sku_compose");
        
        if (record.getSkuId() != null) {
            sql.SET("sku_id = #{skuId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            sql.SET("goods_id = #{goodsId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuKeyId() != null) {
            sql.SET("sku_key_id = #{skuKeyId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuKeyName() != null) {
            sql.SET("sku_key_name = #{skuKeyName,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueId() != null) {
            sql.SET("sku_value_id = #{skuValueId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueName() != null) {
            sql.SET("sku_value_name = #{skuValueName,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku_compose
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, GoodsSkuComposeCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}