package com.tw.mapper;

import com.tw.model.GoodsSku;
import com.tw.model.GoodsSkuCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GoodsSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuSqlProvider.class, method="countByExample")
    long countByExample(GoodsSkuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @DeleteProvider(type=GoodsSkuSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsSkuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_goods_sku",
        "where sku_id = #{skuId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_goods_sku (sku_id, goods_id, ",
        "sku_status, storage_num, ",
        "label_price, market_price, ",
        "cost_price, award_score, ",
        "create_time, bar_code, ",
        "weight, remark, ",
        "sku_img_url, sku_name, ",
        "sku_values)",
        "values (#{skuId,jdbcType=VARCHAR}, #{goodsId,jdbcType=VARCHAR}, ",
        "#{skuStatus,jdbcType=BIT}, #{storageNum,jdbcType=INTEGER}, ",
        "#{labelPrice,jdbcType=DECIMAL}, #{marketPrice,jdbcType=DECIMAL}, ",
        "#{costPrice,jdbcType=DECIMAL}, #{awardScore,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{barCode,jdbcType=VARCHAR}, ",
        "#{weight,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR}, ",
        "#{skuImgUrl,jdbcType=VARCHAR}, #{skuName,jdbcType=VARCHAR}, ",
        "#{skuValues,jdbcType=VARCHAR})"
    })
    int insert(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @InsertProvider(type=GoodsSkuSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_status", property="skuStatus", jdbcType=JdbcType.BIT),
        @Result(column="storage_num", property="storageNum", jdbcType=JdbcType.INTEGER),
        @Result(column="label_price", property="labelPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="cost_price", property="costPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="award_score", property="awardScore", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bar_code", property="barCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight", property="weight", jdbcType=JdbcType.DECIMAL),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_img_url", property="skuImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_name", property="skuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_values", property="skuValues", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsSku> selectByExampleWithRowbounds(GoodsSkuCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @SelectProvider(type=GoodsSkuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_status", property="skuStatus", jdbcType=JdbcType.BIT),
        @Result(column="storage_num", property="storageNum", jdbcType=JdbcType.INTEGER),
        @Result(column="label_price", property="labelPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="cost_price", property="costPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="award_score", property="awardScore", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bar_code", property="barCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight", property="weight", jdbcType=JdbcType.DECIMAL),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_img_url", property="skuImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_name", property="skuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_values", property="skuValues", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsSku> selectByExample(GoodsSkuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "sku_id, goods_id, sku_status, storage_num, label_price, market_price, cost_price, ",
        "award_score, create_time, bar_code, weight, remark, sku_img_url, sku_name, sku_values",
        "from twshop_goods_sku",
        "where sku_id = #{skuId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="sku_id", property="skuId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_status", property="skuStatus", jdbcType=JdbcType.BIT),
        @Result(column="storage_num", property="storageNum", jdbcType=JdbcType.INTEGER),
        @Result(column="label_price", property="labelPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="cost_price", property="costPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="award_score", property="awardScore", jdbcType=JdbcType.DECIMAL),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="bar_code", property="barCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight", property="weight", jdbcType=JdbcType.DECIMAL),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_img_url", property="skuImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_name", property="skuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sku_values", property="skuValues", jdbcType=JdbcType.VARCHAR)
    })
    GoodsSku selectByPrimaryKey(String skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsSku record, @Param("example") GoodsSkuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsSku record, @Param("example") GoodsSkuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_goods_sku
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_goods_sku",
        "set goods_id = #{goodsId,jdbcType=VARCHAR},",
          "sku_status = #{skuStatus,jdbcType=BIT},",
          "storage_num = #{storageNum,jdbcType=INTEGER},",
          "label_price = #{labelPrice,jdbcType=DECIMAL},",
          "market_price = #{marketPrice,jdbcType=DECIMAL},",
          "cost_price = #{costPrice,jdbcType=DECIMAL},",
          "award_score = #{awardScore,jdbcType=DECIMAL},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "bar_code = #{barCode,jdbcType=VARCHAR},",
          "weight = #{weight,jdbcType=DECIMAL},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "sku_img_url = #{skuImgUrl,jdbcType=VARCHAR},",
          "sku_name = #{skuName,jdbcType=VARCHAR},",
          "sku_values = #{skuValues,jdbcType=VARCHAR}",
        "where sku_id = #{skuId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(GoodsSku record);
}