package com.tw.model;

import java.math.BigDecimal;
import java.util.Date;

public class UserCoupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.coupon_id
     *
     * @mbg.generated
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.coupon_number
     *
     * @mbg.generated
     */
    private String couponNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.used_time
     *
     * @mbg.generated
     */
    private Date usedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.source_key
     *
     * @mbg.generated
     */
    private String sourceKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.referrer
     *
     * @mbg.generated
     */
    private Integer referrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.coupon_status
     *
     * @mbg.generated
     */
    private Byte couponStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_user_coupon.coupon_price
     *
     * @mbg.generated
     */
    private BigDecimal couponPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.id
     *
     * @return the value of twshop_user_coupon.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.id
     *
     * @param id the value for twshop_user_coupon.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.coupon_id
     *
     * @return the value of twshop_user_coupon.coupon_id
     *
     * @mbg.generated
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.coupon_id
     *
     * @param couponId the value for twshop_user_coupon.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.coupon_number
     *
     * @return the value of twshop_user_coupon.coupon_number
     *
     * @mbg.generated
     */
    public String getCouponNumber() {
        return couponNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.coupon_number
     *
     * @param couponNumber the value for twshop_user_coupon.coupon_number
     *
     * @mbg.generated
     */
    public void setCouponNumber(String couponNumber) {
        this.couponNumber = couponNumber == null ? null : couponNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.user_id
     *
     * @return the value of twshop_user_coupon.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.user_id
     *
     * @param userId the value for twshop_user_coupon.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.used_time
     *
     * @return the value of twshop_user_coupon.used_time
     *
     * @mbg.generated
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.used_time
     *
     * @param usedTime the value for twshop_user_coupon.used_time
     *
     * @mbg.generated
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.add_time
     *
     * @return the value of twshop_user_coupon.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.add_time
     *
     * @param addTime the value for twshop_user_coupon.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.order_id
     *
     * @return the value of twshop_user_coupon.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.order_id
     *
     * @param orderId the value for twshop_user_coupon.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.source_key
     *
     * @return the value of twshop_user_coupon.source_key
     *
     * @mbg.generated
     */
    public String getSourceKey() {
        return sourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.source_key
     *
     * @param sourceKey the value for twshop_user_coupon.source_key
     *
     * @mbg.generated
     */
    public void setSourceKey(String sourceKey) {
        this.sourceKey = sourceKey == null ? null : sourceKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.referrer
     *
     * @return the value of twshop_user_coupon.referrer
     *
     * @mbg.generated
     */
    public Integer getReferrer() {
        return referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.referrer
     *
     * @param referrer the value for twshop_user_coupon.referrer
     *
     * @mbg.generated
     */
    public void setReferrer(Integer referrer) {
        this.referrer = referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.coupon_status
     *
     * @return the value of twshop_user_coupon.coupon_status
     *
     * @mbg.generated
     */
    public Byte getCouponStatus() {
        return couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.coupon_status
     *
     * @param couponStatus the value for twshop_user_coupon.coupon_status
     *
     * @mbg.generated
     */
    public void setCouponStatus(Byte couponStatus) {
        this.couponStatus = couponStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_user_coupon.coupon_price
     *
     * @return the value of twshop_user_coupon.coupon_price
     *
     * @mbg.generated
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_user_coupon.coupon_price
     *
     * @param couponPrice the value for twshop_user_coupon.coupon_price
     *
     * @mbg.generated
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }
}