package com.tw.model;

import java.math.BigDecimal;
import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.first_cat_id
     *
     * @mbg.generated
     */
    private String firstCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.second_cat_id
     *
     * @mbg.generated
     */
    private String secondCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.third_cat_id
     *
     * @mbg.generated
     */
    private String thirdCatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.supplier_id
     *
     * @mbg.generated
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.supplier_name
     *
     * @mbg.generated
     */
    private String supplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.template_id
     *
     * @mbg.generated
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.jingle
     *
     * @mbg.generated
     */
    private String jingle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.real_sale_num
     *
     * @mbg.generated
     */
    private Long realSaleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.sham_sale_num
     *
     * @mbg.generated
     */
    private Long shamSaleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.online_status
     *
     * @mbg.generated
     */
    private String onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.single_status
     *
     * @mbg.generated
     */
    private String singleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.storage_num
     *
     * @mbg.generated
     */
    private Integer storageNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.fav_num
     *
     * @mbg.generated
     */
    private Integer favNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.label_price
     *
     * @mbg.generated
     */
    private BigDecimal labelPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.market_price
     *
     * @mbg.generated
     */
    private BigDecimal marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.cost_price
     *
     * @mbg.generated
     */
    private BigDecimal costPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.goods_img
     *
     * @mbg.generated
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.goods_code
     *
     * @mbg.generated
     */
    private String goodsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.weight
     *
     * @mbg.generated
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.goods_type
     *
     * @mbg.generated
     */
    private String goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.video_url
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.video_name
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.cover_name
     *
     * @mbg.generated
     */
    private String coverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.cover_url
     *
     * @mbg.generated
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.file_id
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.brand_id
     *
     * @mbg.generated
     */
    private String brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.column_id
     *
     * @mbg.generated
     */
    private String columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.qrcode_url
     *
     * @mbg.generated
     */
    private String qrcodeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.sort
     *
     * @mbg.generated
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.sku_key_value
     *
     * @mbg.generated
     */
    private String skuKeyValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.goods_brief
     *
     * @mbg.generated
     */
    private String goodsBrief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.hot_status
     *
     * @mbg.generated
     */
    private String hotStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods.goods_desc
     *
     * @mbg.generated
     */
    private String goodsDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.goods_id
     *
     * @return the value of twshop_goods.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.goods_id
     *
     * @param goodsId the value for twshop_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.first_cat_id
     *
     * @return the value of twshop_goods.first_cat_id
     *
     * @mbg.generated
     */
    public String getFirstCatId() {
        return firstCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.first_cat_id
     *
     * @param firstCatId the value for twshop_goods.first_cat_id
     *
     * @mbg.generated
     */
    public void setFirstCatId(String firstCatId) {
        this.firstCatId = firstCatId == null ? null : firstCatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.second_cat_id
     *
     * @return the value of twshop_goods.second_cat_id
     *
     * @mbg.generated
     */
    public String getSecondCatId() {
        return secondCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.second_cat_id
     *
     * @param secondCatId the value for twshop_goods.second_cat_id
     *
     * @mbg.generated
     */
    public void setSecondCatId(String secondCatId) {
        this.secondCatId = secondCatId == null ? null : secondCatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.third_cat_id
     *
     * @return the value of twshop_goods.third_cat_id
     *
     * @mbg.generated
     */
    public String getThirdCatId() {
        return thirdCatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.third_cat_id
     *
     * @param thirdCatId the value for twshop_goods.third_cat_id
     *
     * @mbg.generated
     */
    public void setThirdCatId(String thirdCatId) {
        this.thirdCatId = thirdCatId == null ? null : thirdCatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.supplier_id
     *
     * @return the value of twshop_goods.supplier_id
     *
     * @mbg.generated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.supplier_id
     *
     * @param supplierId the value for twshop_goods.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.supplier_name
     *
     * @return the value of twshop_goods.supplier_name
     *
     * @mbg.generated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.supplier_name
     *
     * @param supplierName the value for twshop_goods.supplier_name
     *
     * @mbg.generated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.template_id
     *
     * @return the value of twshop_goods.template_id
     *
     * @mbg.generated
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.template_id
     *
     * @param templateId the value for twshop_goods.template_id
     *
     * @mbg.generated
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.goods_name
     *
     * @return the value of twshop_goods.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.goods_name
     *
     * @param goodsName the value for twshop_goods.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.jingle
     *
     * @return the value of twshop_goods.jingle
     *
     * @mbg.generated
     */
    public String getJingle() {
        return jingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.jingle
     *
     * @param jingle the value for twshop_goods.jingle
     *
     * @mbg.generated
     */
    public void setJingle(String jingle) {
        this.jingle = jingle == null ? null : jingle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.real_sale_num
     *
     * @return the value of twshop_goods.real_sale_num
     *
     * @mbg.generated
     */
    public Long getRealSaleNum() {
        return realSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.real_sale_num
     *
     * @param realSaleNum the value for twshop_goods.real_sale_num
     *
     * @mbg.generated
     */
    public void setRealSaleNum(Long realSaleNum) {
        this.realSaleNum = realSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.sham_sale_num
     *
     * @return the value of twshop_goods.sham_sale_num
     *
     * @mbg.generated
     */
    public Long getShamSaleNum() {
        return shamSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.sham_sale_num
     *
     * @param shamSaleNum the value for twshop_goods.sham_sale_num
     *
     * @mbg.generated
     */
    public void setShamSaleNum(Long shamSaleNum) {
        this.shamSaleNum = shamSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.online_status
     *
     * @return the value of twshop_goods.online_status
     *
     * @mbg.generated
     */
    public String getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.online_status
     *
     * @param onlineStatus the value for twshop_goods.online_status
     *
     * @mbg.generated
     */
    public void setOnlineStatus(String onlineStatus) {
        this.onlineStatus = onlineStatus == null ? null : onlineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.single_status
     *
     * @return the value of twshop_goods.single_status
     *
     * @mbg.generated
     */
    public String getSingleStatus() {
        return singleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.single_status
     *
     * @param singleStatus the value for twshop_goods.single_status
     *
     * @mbg.generated
     */
    public void setSingleStatus(String singleStatus) {
        this.singleStatus = singleStatus == null ? null : singleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.storage_num
     *
     * @return the value of twshop_goods.storage_num
     *
     * @mbg.generated
     */
    public Integer getStorageNum() {
        return storageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.storage_num
     *
     * @param storageNum the value for twshop_goods.storage_num
     *
     * @mbg.generated
     */
    public void setStorageNum(Integer storageNum) {
        this.storageNum = storageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.fav_num
     *
     * @return the value of twshop_goods.fav_num
     *
     * @mbg.generated
     */
    public Integer getFavNum() {
        return favNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.fav_num
     *
     * @param favNum the value for twshop_goods.fav_num
     *
     * @mbg.generated
     */
    public void setFavNum(Integer favNum) {
        this.favNum = favNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.label_price
     *
     * @return the value of twshop_goods.label_price
     *
     * @mbg.generated
     */
    public BigDecimal getLabelPrice() {
        return labelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.label_price
     *
     * @param labelPrice the value for twshop_goods.label_price
     *
     * @mbg.generated
     */
    public void setLabelPrice(BigDecimal labelPrice) {
        this.labelPrice = labelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.market_price
     *
     * @return the value of twshop_goods.market_price
     *
     * @mbg.generated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.market_price
     *
     * @param marketPrice the value for twshop_goods.market_price
     *
     * @mbg.generated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.cost_price
     *
     * @return the value of twshop_goods.cost_price
     *
     * @mbg.generated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.cost_price
     *
     * @param costPrice the value for twshop_goods.cost_price
     *
     * @mbg.generated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.goods_img
     *
     * @return the value of twshop_goods.goods_img
     *
     * @mbg.generated
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.goods_img
     *
     * @param goodsImg the value for twshop_goods.goods_img
     *
     * @mbg.generated
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.goods_code
     *
     * @return the value of twshop_goods.goods_code
     *
     * @mbg.generated
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.goods_code
     *
     * @param goodsCode the value for twshop_goods.goods_code
     *
     * @mbg.generated
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode == null ? null : goodsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.weight
     *
     * @return the value of twshop_goods.weight
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.weight
     *
     * @param weight the value for twshop_goods.weight
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.goods_type
     *
     * @return the value of twshop_goods.goods_type
     *
     * @mbg.generated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.goods_type
     *
     * @param goodsType the value for twshop_goods.goods_type
     *
     * @mbg.generated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.remark
     *
     * @return the value of twshop_goods.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.remark
     *
     * @param remark the value for twshop_goods.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.video_url
     *
     * @return the value of twshop_goods.video_url
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.video_url
     *
     * @param videoUrl the value for twshop_goods.video_url
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.video_name
     *
     * @return the value of twshop_goods.video_name
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.video_name
     *
     * @param videoName the value for twshop_goods.video_name
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.cover_name
     *
     * @return the value of twshop_goods.cover_name
     *
     * @mbg.generated
     */
    public String getCoverName() {
        return coverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.cover_name
     *
     * @param coverName the value for twshop_goods.cover_name
     *
     * @mbg.generated
     */
    public void setCoverName(String coverName) {
        this.coverName = coverName == null ? null : coverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.cover_url
     *
     * @return the value of twshop_goods.cover_url
     *
     * @mbg.generated
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.cover_url
     *
     * @param coverUrl the value for twshop_goods.cover_url
     *
     * @mbg.generated
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.file_id
     *
     * @return the value of twshop_goods.file_id
     *
     * @mbg.generated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.file_id
     *
     * @param fileId the value for twshop_goods.file_id
     *
     * @mbg.generated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.brand_id
     *
     * @return the value of twshop_goods.brand_id
     *
     * @mbg.generated
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.brand_id
     *
     * @param brandId the value for twshop_goods.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.column_id
     *
     * @return the value of twshop_goods.column_id
     *
     * @mbg.generated
     */
    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.column_id
     *
     * @param columnId the value for twshop_goods.column_id
     *
     * @mbg.generated
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.qrcode_url
     *
     * @return the value of twshop_goods.qrcode_url
     *
     * @mbg.generated
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.qrcode_url
     *
     * @param qrcodeUrl the value for twshop_goods.qrcode_url
     *
     * @mbg.generated
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.sort
     *
     * @return the value of twshop_goods.sort
     *
     * @mbg.generated
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.sort
     *
     * @param sort the value for twshop_goods.sort
     *
     * @mbg.generated
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.sku_key_value
     *
     * @return the value of twshop_goods.sku_key_value
     *
     * @mbg.generated
     */
    public String getSkuKeyValue() {
        return skuKeyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.sku_key_value
     *
     * @param skuKeyValue the value for twshop_goods.sku_key_value
     *
     * @mbg.generated
     */
    public void setSkuKeyValue(String skuKeyValue) {
        this.skuKeyValue = skuKeyValue == null ? null : skuKeyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.create_time
     *
     * @return the value of twshop_goods.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.create_time
     *
     * @param createTime the value for twshop_goods.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.update_time
     *
     * @return the value of twshop_goods.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.update_time
     *
     * @param updateTime the value for twshop_goods.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.keywords
     *
     * @return the value of twshop_goods.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.keywords
     *
     * @param keywords the value for twshop_goods.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.goods_brief
     *
     * @return the value of twshop_goods.goods_brief
     *
     * @mbg.generated
     */
    public String getGoodsBrief() {
        return goodsBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.goods_brief
     *
     * @param goodsBrief the value for twshop_goods.goods_brief
     *
     * @mbg.generated
     */
    public void setGoodsBrief(String goodsBrief) {
        this.goodsBrief = goodsBrief == null ? null : goodsBrief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.hot_status
     *
     * @return the value of twshop_goods.hot_status
     *
     * @mbg.generated
     */
    public String getHotStatus() {
        return hotStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.hot_status
     *
     * @param hotStatus the value for twshop_goods.hot_status
     *
     * @mbg.generated
     */
    public void setHotStatus(String hotStatus) {
        this.hotStatus = hotStatus == null ? null : hotStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods.goods_desc
     *
     * @return the value of twshop_goods.goods_desc
     *
     * @mbg.generated
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods.goods_desc
     *
     * @param goodsDesc the value for twshop_goods.goods_desc
     *
     * @mbg.generated
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }
}