package com.tw.model;

public class GoodsSkuCompose {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_sku_compose.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_sku_compose.sku_id
     *
     * @mbg.generated
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_sku_compose.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_sku_compose.sku_key_id
     *
     * @mbg.generated
     */
    private String skuKeyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_sku_compose.sku_key_name
     *
     * @mbg.generated
     */
    private String skuKeyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_sku_compose.sku_value_id
     *
     * @mbg.generated
     */
    private String skuValueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_sku_compose.sku_value_name
     *
     * @mbg.generated
     */
    private String skuValueName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_sku_compose.id
     *
     * @return the value of twshop_goods_sku_compose.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_sku_compose.id
     *
     * @param id the value for twshop_goods_sku_compose.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_sku_compose.sku_id
     *
     * @return the value of twshop_goods_sku_compose.sku_id
     *
     * @mbg.generated
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_sku_compose.sku_id
     *
     * @param skuId the value for twshop_goods_sku_compose.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_sku_compose.goods_id
     *
     * @return the value of twshop_goods_sku_compose.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_sku_compose.goods_id
     *
     * @param goodsId the value for twshop_goods_sku_compose.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_sku_compose.sku_key_id
     *
     * @return the value of twshop_goods_sku_compose.sku_key_id
     *
     * @mbg.generated
     */
    public String getSkuKeyId() {
        return skuKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_sku_compose.sku_key_id
     *
     * @param skuKeyId the value for twshop_goods_sku_compose.sku_key_id
     *
     * @mbg.generated
     */
    public void setSkuKeyId(String skuKeyId) {
        this.skuKeyId = skuKeyId == null ? null : skuKeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_sku_compose.sku_key_name
     *
     * @return the value of twshop_goods_sku_compose.sku_key_name
     *
     * @mbg.generated
     */
    public String getSkuKeyName() {
        return skuKeyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_sku_compose.sku_key_name
     *
     * @param skuKeyName the value for twshop_goods_sku_compose.sku_key_name
     *
     * @mbg.generated
     */
    public void setSkuKeyName(String skuKeyName) {
        this.skuKeyName = skuKeyName == null ? null : skuKeyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_sku_compose.sku_value_id
     *
     * @return the value of twshop_goods_sku_compose.sku_value_id
     *
     * @mbg.generated
     */
    public String getSkuValueId() {
        return skuValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_sku_compose.sku_value_id
     *
     * @param skuValueId the value for twshop_goods_sku_compose.sku_value_id
     *
     * @mbg.generated
     */
    public void setSkuValueId(String skuValueId) {
        this.skuValueId = skuValueId == null ? null : skuValueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_sku_compose.sku_value_name
     *
     * @return the value of twshop_goods_sku_compose.sku_value_name
     *
     * @mbg.generated
     */
    public String getSkuValueName() {
        return skuValueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_sku_compose.sku_value_name
     *
     * @param skuValueName the value for twshop_goods_sku_compose.sku_value_name
     *
     * @mbg.generated
     */
    public void setSkuValueName(String skuValueName) {
        this.skuValueName = skuValueName == null ? null : skuValueName.trim();
    }
}