package com.tw.model;

public class GoodsAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_attribute.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_attribute.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_attribute.attribute_id
     *
     * @mbg.generated
     */
    private Integer attributeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_attribute.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_attribute.id
     *
     * @return the value of twshop_goods_attribute.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_attribute.id
     *
     * @param id the value for twshop_goods_attribute.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_attribute.goods_id
     *
     * @return the value of twshop_goods_attribute.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_attribute.goods_id
     *
     * @param goodsId the value for twshop_goods_attribute.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_attribute.attribute_id
     *
     * @return the value of twshop_goods_attribute.attribute_id
     *
     * @mbg.generated
     */
    public Integer getAttributeId() {
        return attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_attribute.attribute_id
     *
     * @param attributeId the value for twshop_goods_attribute.attribute_id
     *
     * @mbg.generated
     */
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_attribute.value
     *
     * @return the value of twshop_goods_attribute.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_attribute.value
     *
     * @param value the value for twshop_goods_attribute.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}