package com.tw.model;

public class GoodsGallery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_gallery.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    private String imgDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_gallery.sort_order
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column twshop_goods_gallery.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_gallery.id
     *
     * @return the value of twshop_goods_gallery.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_gallery.id
     *
     * @param id the value for twshop_goods_gallery.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_gallery.goods_id
     *
     * @return the value of twshop_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_gallery.goods_id
     *
     * @param goodsId the value for twshop_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_gallery.img_desc
     *
     * @return the value of twshop_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    public String getImgDesc() {
        return imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_gallery.img_desc
     *
     * @param imgDesc the value for twshop_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc == null ? null : imgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_gallery.sort_order
     *
     * @return the value of twshop_goods_gallery.sort_order
     *
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_gallery.sort_order
     *
     * @param sortOrder the value for twshop_goods_gallery.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column twshop_goods_gallery.img_url
     *
     * @return the value of twshop_goods_gallery.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column twshop_goods_gallery.img_url
     *
     * @param imgUrl the value for twshop_goods_gallery.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}