package com.tw.mapper;

import com.tw.model.Cart;
import com.tw.model.CartCriteria.Criteria;
import com.tw.model.CartCriteria.Criterion;
import com.tw.model.CartCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CartSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    public String countByExample(CartCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("twshop_cart");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    public String deleteByExample(CartCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("twshop_cart");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    public String insertSelective(Cart record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("twshop_cart");
        
        if (record.getCartId() != null) {
            sql.VALUES("cart_id", "#{cartId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            sql.VALUES("goods_id", "#{goodsId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsName() != null) {
            sql.VALUES("goods_name", "#{goodsName,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuId() != null) {
            sql.VALUES("sku_id", "#{skuId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueText() != null) {
            sql.VALUES("sku_value_text", "#{skuValueText,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsImgUrl() != null) {
            sql.VALUES("goods_img_url", "#{goodsImgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getNumber() != null) {
            sql.VALUES("number", "#{number,jdbcType=INTEGER}");
        }
        
        if (record.getLabelPrice() != null) {
            sql.VALUES("label_price", "#{labelPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketPrice() != null) {
            sql.VALUES("market_price", "#{marketPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getChecked() != null) {
            sql.VALUES("checked", "#{checked,jdbcType=INTEGER}");
        }
        
        if (record.getWay() != null) {
            sql.VALUES("way", "#{way,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    public String selectByExample(CartCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("cart_id");
        } else {
            sql.SELECT("cart_id");
        }
        sql.SELECT("user_id");
        sql.SELECT("goods_id");
        sql.SELECT("goods_name");
        sql.SELECT("sku_id");
        sql.SELECT("sku_value_text");
        sql.SELECT("goods_img_url");
        sql.SELECT("number");
        sql.SELECT("label_price");
        sql.SELECT("market_price");
        sql.SELECT("checked");
        sql.SELECT("way");
        sql.FROM("twshop_cart");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Cart record = (Cart) parameter.get("record");
        CartCriteria example = (CartCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("twshop_cart");
        
        if (record.getCartId() != null) {
            sql.SET("cart_id = #{record.cartId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            sql.SET("goods_id = #{record.goodsId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsName() != null) {
            sql.SET("goods_name = #{record.goodsName,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuId() != null) {
            sql.SET("sku_id = #{record.skuId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueText() != null) {
            sql.SET("sku_value_text = #{record.skuValueText,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsImgUrl() != null) {
            sql.SET("goods_img_url = #{record.goodsImgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getNumber() != null) {
            sql.SET("number = #{record.number,jdbcType=INTEGER}");
        }
        
        if (record.getLabelPrice() != null) {
            sql.SET("label_price = #{record.labelPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketPrice() != null) {
            sql.SET("market_price = #{record.marketPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getChecked() != null) {
            sql.SET("checked = #{record.checked,jdbcType=INTEGER}");
        }
        
        if (record.getWay() != null) {
            sql.SET("way = #{record.way,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_cart");
        
        sql.SET("cart_id = #{record.cartId,jdbcType=INTEGER}");
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("goods_id = #{record.goodsId,jdbcType=VARCHAR}");
        sql.SET("goods_name = #{record.goodsName,jdbcType=VARCHAR}");
        sql.SET("sku_id = #{record.skuId,jdbcType=VARCHAR}");
        sql.SET("sku_value_text = #{record.skuValueText,jdbcType=VARCHAR}");
        sql.SET("goods_img_url = #{record.goodsImgUrl,jdbcType=VARCHAR}");
        sql.SET("number = #{record.number,jdbcType=INTEGER}");
        sql.SET("label_price = #{record.labelPrice,jdbcType=DECIMAL}");
        sql.SET("market_price = #{record.marketPrice,jdbcType=DECIMAL}");
        sql.SET("checked = #{record.checked,jdbcType=INTEGER}");
        sql.SET("way = #{record.way,jdbcType=INTEGER}");
        
        CartCriteria example = (CartCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Cart record) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_cart");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            sql.SET("goods_id = #{goodsId,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsName() != null) {
            sql.SET("goods_name = #{goodsName,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuId() != null) {
            sql.SET("sku_id = #{skuId,jdbcType=VARCHAR}");
        }
        
        if (record.getSkuValueText() != null) {
            sql.SET("sku_value_text = #{skuValueText,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsImgUrl() != null) {
            sql.SET("goods_img_url = #{goodsImgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getNumber() != null) {
            sql.SET("number = #{number,jdbcType=INTEGER}");
        }
        
        if (record.getLabelPrice() != null) {
            sql.SET("label_price = #{labelPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getMarketPrice() != null) {
            sql.SET("market_price = #{marketPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getChecked() != null) {
            sql.SET("checked = #{checked,jdbcType=INTEGER}");
        }
        
        if (record.getWay() != null) {
            sql.SET("way = #{way,jdbcType=INTEGER}");
        }
        
        sql.WHERE("cart_id = #{cartId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_cart
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, CartCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}