package com.tw.mapper;

import com.tw.model.Coupon;
import com.tw.model.CouponCriteria.Criteria;
import com.tw.model.CouponCriteria.Criterion;
import com.tw.model.CouponCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class CouponSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    public String countByExample(CouponCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("twshop_coupon");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    public String deleteByExample(CouponCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("twshop_coupon");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    public String insertSelective(Coupon record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("twshop_coupon");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeMoney() != null) {
            sql.VALUES("type_money", "#{typeMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getSendType() != null) {
            sql.VALUES("send_type", "#{sendType,jdbcType=TINYINT}");
        }
        
        if (record.getMinAmount() != null) {
            sql.VALUES("min_amount", "#{minAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getMaxAmount() != null) {
            sql.VALUES("max_amount", "#{maxAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getSendStartDate() != null) {
            sql.VALUES("send_start_date", "#{sendStartDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendEndDate() != null) {
            sql.VALUES("send_end_date", "#{sendEndDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseStartDate() != null) {
            sql.VALUES("use_start_date", "#{useStartDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseEndDate() != null) {
            sql.VALUES("use_end_date", "#{useEndDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMinGoodsAmount() != null) {
            sql.VALUES("min_goods_amount", "#{minGoodsAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getMinTransmitNum() != null) {
            sql.VALUES("min_transmit_num", "#{minTransmitNum,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    public String selectByExample(CouponCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("name");
        sql.SELECT("type_money");
        sql.SELECT("send_type");
        sql.SELECT("min_amount");
        sql.SELECT("max_amount");
        sql.SELECT("send_start_date");
        sql.SELECT("send_end_date");
        sql.SELECT("use_start_date");
        sql.SELECT("use_end_date");
        sql.SELECT("min_goods_amount");
        sql.SELECT("min_transmit_num");
        sql.FROM("twshop_coupon");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Coupon record = (Coupon) parameter.get("record");
        CouponCriteria example = (CouponCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("twshop_coupon");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeMoney() != null) {
            sql.SET("type_money = #{record.typeMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getSendType() != null) {
            sql.SET("send_type = #{record.sendType,jdbcType=TINYINT}");
        }
        
        if (record.getMinAmount() != null) {
            sql.SET("min_amount = #{record.minAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getMaxAmount() != null) {
            sql.SET("max_amount = #{record.maxAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getSendStartDate() != null) {
            sql.SET("send_start_date = #{record.sendStartDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendEndDate() != null) {
            sql.SET("send_end_date = #{record.sendEndDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseStartDate() != null) {
            sql.SET("use_start_date = #{record.useStartDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseEndDate() != null) {
            sql.SET("use_end_date = #{record.useEndDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMinGoodsAmount() != null) {
            sql.SET("min_goods_amount = #{record.minGoodsAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getMinTransmitNum() != null) {
            sql.SET("min_transmit_num = #{record.minTransmitNum,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_coupon");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("type_money = #{record.typeMoney,jdbcType=DECIMAL}");
        sql.SET("send_type = #{record.sendType,jdbcType=TINYINT}");
        sql.SET("min_amount = #{record.minAmount,jdbcType=DECIMAL}");
        sql.SET("max_amount = #{record.maxAmount,jdbcType=DECIMAL}");
        sql.SET("send_start_date = #{record.sendStartDate,jdbcType=TIMESTAMP}");
        sql.SET("send_end_date = #{record.sendEndDate,jdbcType=TIMESTAMP}");
        sql.SET("use_start_date = #{record.useStartDate,jdbcType=TIMESTAMP}");
        sql.SET("use_end_date = #{record.useEndDate,jdbcType=TIMESTAMP}");
        sql.SET("min_goods_amount = #{record.minGoodsAmount,jdbcType=DECIMAL}");
        sql.SET("min_transmit_num = #{record.minTransmitNum,jdbcType=INTEGER}");
        
        CouponCriteria example = (CouponCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Coupon record) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_coupon");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeMoney() != null) {
            sql.SET("type_money = #{typeMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getSendType() != null) {
            sql.SET("send_type = #{sendType,jdbcType=TINYINT}");
        }
        
        if (record.getMinAmount() != null) {
            sql.SET("min_amount = #{minAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getMaxAmount() != null) {
            sql.SET("max_amount = #{maxAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getSendStartDate() != null) {
            sql.SET("send_start_date = #{sendStartDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSendEndDate() != null) {
            sql.SET("send_end_date = #{sendEndDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseStartDate() != null) {
            sql.SET("use_start_date = #{useStartDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUseEndDate() != null) {
            sql.SET("use_end_date = #{useEndDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMinGoodsAmount() != null) {
            sql.SET("min_goods_amount = #{minGoodsAmount,jdbcType=DECIMAL}");
        }
        
        if (record.getMinTransmitNum() != null) {
            sql.SET("min_transmit_num = #{minTransmitNum,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, CouponCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}