package com.tw.mapper;

import com.tw.model.Coupon;
import com.tw.model.CouponCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=CouponSqlProvider.class, method="countByExample")
    long countByExample(CouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @DeleteProvider(type=CouponSqlProvider.class, method="deleteByExample")
    int deleteByExample(CouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_coupon (id, name, ",
        "type_money, send_type, ",
        "min_amount, max_amount, ",
        "send_start_date, send_end_date, ",
        "use_start_date, use_end_date, ",
        "min_goods_amount, min_transmit_num)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{typeMoney,jdbcType=DECIMAL}, #{sendType,jdbcType=TINYINT}, ",
        "#{minAmount,jdbcType=DECIMAL}, #{maxAmount,jdbcType=DECIMAL}, ",
        "#{sendStartDate,jdbcType=TIMESTAMP}, #{sendEndDate,jdbcType=TIMESTAMP}, ",
        "#{useStartDate,jdbcType=TIMESTAMP}, #{useEndDate,jdbcType=TIMESTAMP}, ",
        "#{minGoodsAmount,jdbcType=DECIMAL}, #{minTransmitNum,jdbcType=INTEGER})"
    })
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @InsertProvider(type=CouponSqlProvider.class, method="insertSelective")
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=CouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_money", property="typeMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="send_type", property="sendType", jdbcType=JdbcType.TINYINT),
        @Result(column="min_amount", property="minAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="max_amount", property="maxAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="send_start_date", property="sendStartDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="send_end_date", property="sendEndDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="use_start_date", property="useStartDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="use_end_date", property="useEndDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="min_goods_amount", property="minGoodsAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="min_transmit_num", property="minTransmitNum", jdbcType=JdbcType.INTEGER)
    })
    List<Coupon> selectByExampleWithRowbounds(CouponCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=CouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_money", property="typeMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="send_type", property="sendType", jdbcType=JdbcType.TINYINT),
        @Result(column="min_amount", property="minAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="max_amount", property="maxAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="send_start_date", property="sendStartDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="send_end_date", property="sendEndDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="use_start_date", property="useStartDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="use_end_date", property="useEndDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="min_goods_amount", property="minGoodsAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="min_transmit_num", property="minTransmitNum", jdbcType=JdbcType.INTEGER)
    })
    List<Coupon> selectByExample(CouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, type_money, send_type, min_amount, max_amount, send_start_date, send_end_date, ",
        "use_start_date, use_end_date, min_goods_amount, min_transmit_num",
        "from twshop_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type_money", property="typeMoney", jdbcType=JdbcType.DECIMAL),
        @Result(column="send_type", property="sendType", jdbcType=JdbcType.TINYINT),
        @Result(column="min_amount", property="minAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="max_amount", property="maxAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="send_start_date", property="sendStartDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="send_end_date", property="sendEndDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="use_start_date", property="useStartDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="use_end_date", property="useEndDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="min_goods_amount", property="minGoodsAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="min_transmit_num", property="minTransmitNum", jdbcType=JdbcType.INTEGER)
    })
    Coupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Coupon record, @Param("example") CouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Coupon record, @Param("example") CouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=CouponSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_coupon
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_coupon",
        "set name = #{name,jdbcType=VARCHAR},",
          "type_money = #{typeMoney,jdbcType=DECIMAL},",
          "send_type = #{sendType,jdbcType=TINYINT},",
          "min_amount = #{minAmount,jdbcType=DECIMAL},",
          "max_amount = #{maxAmount,jdbcType=DECIMAL},",
          "send_start_date = #{sendStartDate,jdbcType=TIMESTAMP},",
          "send_end_date = #{sendEndDate,jdbcType=TIMESTAMP},",
          "use_start_date = #{useStartDate,jdbcType=TIMESTAMP},",
          "use_end_date = #{useEndDate,jdbcType=TIMESTAMP},",
          "min_goods_amount = #{minGoodsAmount,jdbcType=DECIMAL},",
          "min_transmit_num = #{minTransmitNum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Coupon record);
}