package com.tw.mapper;

import com.tw.model.Order;
import com.tw.model.OrderCriteria.Criteria;
import com.tw.model.OrderCriteria.Criterion;
import com.tw.model.OrderCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class OrderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    public String countByExample(OrderCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("twshop_order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    public String deleteByExample(OrderCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("twshop_order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    public String insertSelective(Order record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("twshop_order");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getOrderSn() != null) {
            sql.VALUES("order_sn", "#{orderSn,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderStatus() != null) {
            sql.VALUES("order_status", "#{orderStatus,jdbcType=INTEGER}");
        }
        
        if (record.getShippingStatus() != null) {
            sql.VALUES("shipping_status", "#{shippingStatus,jdbcType=INTEGER}");
        }
        
        if (record.getPayStatus() != null) {
            sql.VALUES("pay_status", "#{payStatus,jdbcType=INTEGER}");
        }
        
        if (record.getConsignee() != null) {
            sql.VALUES("consignee", "#{consignee,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            sql.VALUES("country", "#{country,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            sql.VALUES("province", "#{province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.VALUES("city", "#{city,jdbcType=VARCHAR}");
        }
        
        if (record.getDistrict() != null) {
            sql.VALUES("district", "#{district,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.VALUES("mobile", "#{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getPostscript() != null) {
            sql.VALUES("postscript", "#{postscript,jdbcType=VARCHAR}");
        }
        
        if (record.getShippingId() != null) {
            sql.VALUES("shipping_id", "#{shippingId,jdbcType=TINYINT}");
        }
        
        if (record.getShippingName() != null) {
            sql.VALUES("shipping_name", "#{shippingName,jdbcType=VARCHAR}");
        }
        
        if (record.getPayId() != null) {
            sql.VALUES("pay_id", "#{payId,jdbcType=VARCHAR}");
        }
        
        if (record.getPayName() != null) {
            sql.VALUES("pay_name", "#{payName,jdbcType=VARCHAR}");
        }
        
        if (record.getShippingFee() != null) {
            sql.VALUES("shipping_fee", "#{shippingFee,jdbcType=DECIMAL}");
        }
        
        if (record.getActualPrice() != null) {
            sql.VALUES("actual_price", "#{actualPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getIntegral() != null) {
            sql.VALUES("integral", "#{integral,jdbcType=INTEGER}");
        }
        
        if (record.getIntegralMoney() != null) {
            sql.VALUES("integral_money", "#{integralMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.VALUES("order_price", "#{orderPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getGoodsPrice() != null) {
            sql.VALUES("goods_price", "#{goodsPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAddTime() != null) {
            sql.VALUES("add_time", "#{addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getConfirmTime() != null) {
            sql.VALUES("confirm_time", "#{confirmTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPayTime() != null) {
            sql.VALUES("pay_time", "#{payTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFreightPrice() != null) {
            sql.VALUES("freight_price", "#{freightPrice,jdbcType=INTEGER}");
        }
        
        if (record.getCouponId() != null) {
            sql.VALUES("coupon_id", "#{couponId,jdbcType=INTEGER}");
        }
        
        if (record.getParentId() != null) {
            sql.VALUES("parent_id", "#{parentId,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPrice() != null) {
            sql.VALUES("coupon_price", "#{couponPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getCallbackStatus() != null) {
            sql.VALUES("callback_status", "#{callbackStatus,jdbcType=CHAR}");
        }
        
        if (record.getShippingNo() != null) {
            sql.VALUES("shipping_no", "#{shippingNo,jdbcType=VARCHAR}");
        }
        
        if (record.getFullCutPrice() != null) {
            sql.VALUES("full_cut_price", "#{fullCutPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderType() != null) {
            sql.VALUES("order_type", "#{orderType,jdbcType=VARCHAR}");
        }
        
        if (record.getBrandId() != null) {
            sql.VALUES("brand_id", "#{brandId,jdbcType=INTEGER}");
        }
        
        if (record.getSettlementTotalFee() != null) {
            sql.VALUES("settlement_total_fee", "#{settlementTotalFee,jdbcType=INTEGER}");
        }
        
        if (record.getAllPrice() != null) {
            sql.VALUES("all_price", "#{allPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAllOrderId() != null) {
            sql.VALUES("all_order_id", "#{allOrderId,jdbcType=VARCHAR}");
        }
        
        if (record.getPromoterId() != null) {
            sql.VALUES("promoter_id", "#{promoterId,jdbcType=INTEGER}");
        }
        
        if (record.getBrokerage() != null) {
            sql.VALUES("brokerage", "#{brokerage,jdbcType=DECIMAL}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    public String selectByExample(OrderCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("order_sn");
        sql.SELECT("user_id");
        sql.SELECT("order_status");
        sql.SELECT("shipping_status");
        sql.SELECT("pay_status");
        sql.SELECT("consignee");
        sql.SELECT("country");
        sql.SELECT("province");
        sql.SELECT("city");
        sql.SELECT("district");
        sql.SELECT("address");
        sql.SELECT("mobile");
        sql.SELECT("postscript");
        sql.SELECT("shipping_id");
        sql.SELECT("shipping_name");
        sql.SELECT("pay_id");
        sql.SELECT("pay_name");
        sql.SELECT("shipping_fee");
        sql.SELECT("actual_price");
        sql.SELECT("integral");
        sql.SELECT("integral_money");
        sql.SELECT("order_price");
        sql.SELECT("goods_price");
        sql.SELECT("add_time");
        sql.SELECT("confirm_time");
        sql.SELECT("pay_time");
        sql.SELECT("freight_price");
        sql.SELECT("coupon_id");
        sql.SELECT("parent_id");
        sql.SELECT("coupon_price");
        sql.SELECT("callback_status");
        sql.SELECT("shipping_no");
        sql.SELECT("full_cut_price");
        sql.SELECT("order_type");
        sql.SELECT("brand_id");
        sql.SELECT("settlement_total_fee");
        sql.SELECT("all_price");
        sql.SELECT("all_order_id");
        sql.SELECT("promoter_id");
        sql.SELECT("brokerage");
        sql.FROM("twshop_order");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Order record = (Order) parameter.get("record");
        OrderCriteria example = (OrderCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("twshop_order");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getOrderSn() != null) {
            sql.SET("order_sn = #{record.orderSn,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderStatus() != null) {
            sql.SET("order_status = #{record.orderStatus,jdbcType=INTEGER}");
        }
        
        if (record.getShippingStatus() != null) {
            sql.SET("shipping_status = #{record.shippingStatus,jdbcType=INTEGER}");
        }
        
        if (record.getPayStatus() != null) {
            sql.SET("pay_status = #{record.payStatus,jdbcType=INTEGER}");
        }
        
        if (record.getConsignee() != null) {
            sql.SET("consignee = #{record.consignee,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            sql.SET("country = #{record.country,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            sql.SET("province = #{record.province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.SET("city = #{record.city,jdbcType=VARCHAR}");
        }
        
        if (record.getDistrict() != null) {
            sql.SET("district = #{record.district,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.SET("address = #{record.address,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getPostscript() != null) {
            sql.SET("postscript = #{record.postscript,jdbcType=VARCHAR}");
        }
        
        if (record.getShippingId() != null) {
            sql.SET("shipping_id = #{record.shippingId,jdbcType=TINYINT}");
        }
        
        if (record.getShippingName() != null) {
            sql.SET("shipping_name = #{record.shippingName,jdbcType=VARCHAR}");
        }
        
        if (record.getPayId() != null) {
            sql.SET("pay_id = #{record.payId,jdbcType=VARCHAR}");
        }
        
        if (record.getPayName() != null) {
            sql.SET("pay_name = #{record.payName,jdbcType=VARCHAR}");
        }
        
        if (record.getShippingFee() != null) {
            sql.SET("shipping_fee = #{record.shippingFee,jdbcType=DECIMAL}");
        }
        
        if (record.getActualPrice() != null) {
            sql.SET("actual_price = #{record.actualPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getIntegral() != null) {
            sql.SET("integral = #{record.integral,jdbcType=INTEGER}");
        }
        
        if (record.getIntegralMoney() != null) {
            sql.SET("integral_money = #{record.integralMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.SET("order_price = #{record.orderPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getGoodsPrice() != null) {
            sql.SET("goods_price = #{record.goodsPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAddTime() != null) {
            sql.SET("add_time = #{record.addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getConfirmTime() != null) {
            sql.SET("confirm_time = #{record.confirmTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPayTime() != null) {
            sql.SET("pay_time = #{record.payTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFreightPrice() != null) {
            sql.SET("freight_price = #{record.freightPrice,jdbcType=INTEGER}");
        }
        
        if (record.getCouponId() != null) {
            sql.SET("coupon_id = #{record.couponId,jdbcType=INTEGER}");
        }
        
        if (record.getParentId() != null) {
            sql.SET("parent_id = #{record.parentId,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPrice() != null) {
            sql.SET("coupon_price = #{record.couponPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getCallbackStatus() != null) {
            sql.SET("callback_status = #{record.callbackStatus,jdbcType=CHAR}");
        }
        
        if (record.getShippingNo() != null) {
            sql.SET("shipping_no = #{record.shippingNo,jdbcType=VARCHAR}");
        }
        
        if (record.getFullCutPrice() != null) {
            sql.SET("full_cut_price = #{record.fullCutPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderType() != null) {
            sql.SET("order_type = #{record.orderType,jdbcType=VARCHAR}");
        }
        
        if (record.getBrandId() != null) {
            sql.SET("brand_id = #{record.brandId,jdbcType=INTEGER}");
        }
        
        if (record.getSettlementTotalFee() != null) {
            sql.SET("settlement_total_fee = #{record.settlementTotalFee,jdbcType=INTEGER}");
        }
        
        if (record.getAllPrice() != null) {
            sql.SET("all_price = #{record.allPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAllOrderId() != null) {
            sql.SET("all_order_id = #{record.allOrderId,jdbcType=VARCHAR}");
        }
        
        if (record.getPromoterId() != null) {
            sql.SET("promoter_id = #{record.promoterId,jdbcType=INTEGER}");
        }
        
        if (record.getBrokerage() != null) {
            sql.SET("brokerage = #{record.brokerage,jdbcType=DECIMAL}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_order");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("order_sn = #{record.orderSn,jdbcType=VARCHAR}");
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("order_status = #{record.orderStatus,jdbcType=INTEGER}");
        sql.SET("shipping_status = #{record.shippingStatus,jdbcType=INTEGER}");
        sql.SET("pay_status = #{record.payStatus,jdbcType=INTEGER}");
        sql.SET("consignee = #{record.consignee,jdbcType=VARCHAR}");
        sql.SET("country = #{record.country,jdbcType=VARCHAR}");
        sql.SET("province = #{record.province,jdbcType=VARCHAR}");
        sql.SET("city = #{record.city,jdbcType=VARCHAR}");
        sql.SET("district = #{record.district,jdbcType=VARCHAR}");
        sql.SET("address = #{record.address,jdbcType=VARCHAR}");
        sql.SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        sql.SET("postscript = #{record.postscript,jdbcType=VARCHAR}");
        sql.SET("shipping_id = #{record.shippingId,jdbcType=TINYINT}");
        sql.SET("shipping_name = #{record.shippingName,jdbcType=VARCHAR}");
        sql.SET("pay_id = #{record.payId,jdbcType=VARCHAR}");
        sql.SET("pay_name = #{record.payName,jdbcType=VARCHAR}");
        sql.SET("shipping_fee = #{record.shippingFee,jdbcType=DECIMAL}");
        sql.SET("actual_price = #{record.actualPrice,jdbcType=DECIMAL}");
        sql.SET("integral = #{record.integral,jdbcType=INTEGER}");
        sql.SET("integral_money = #{record.integralMoney,jdbcType=DECIMAL}");
        sql.SET("order_price = #{record.orderPrice,jdbcType=DECIMAL}");
        sql.SET("goods_price = #{record.goodsPrice,jdbcType=DECIMAL}");
        sql.SET("add_time = #{record.addTime,jdbcType=TIMESTAMP}");
        sql.SET("confirm_time = #{record.confirmTime,jdbcType=TIMESTAMP}");
        sql.SET("pay_time = #{record.payTime,jdbcType=TIMESTAMP}");
        sql.SET("freight_price = #{record.freightPrice,jdbcType=INTEGER}");
        sql.SET("coupon_id = #{record.couponId,jdbcType=INTEGER}");
        sql.SET("parent_id = #{record.parentId,jdbcType=INTEGER}");
        sql.SET("coupon_price = #{record.couponPrice,jdbcType=DECIMAL}");
        sql.SET("callback_status = #{record.callbackStatus,jdbcType=CHAR}");
        sql.SET("shipping_no = #{record.shippingNo,jdbcType=VARCHAR}");
        sql.SET("full_cut_price = #{record.fullCutPrice,jdbcType=DECIMAL}");
        sql.SET("order_type = #{record.orderType,jdbcType=VARCHAR}");
        sql.SET("brand_id = #{record.brandId,jdbcType=INTEGER}");
        sql.SET("settlement_total_fee = #{record.settlementTotalFee,jdbcType=INTEGER}");
        sql.SET("all_price = #{record.allPrice,jdbcType=DECIMAL}");
        sql.SET("all_order_id = #{record.allOrderId,jdbcType=VARCHAR}");
        sql.SET("promoter_id = #{record.promoterId,jdbcType=INTEGER}");
        sql.SET("brokerage = #{record.brokerage,jdbcType=DECIMAL}");
        
        OrderCriteria example = (OrderCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Order record) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_order");
        
        if (record.getOrderSn() != null) {
            sql.SET("order_sn = #{orderSn,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderStatus() != null) {
            sql.SET("order_status = #{orderStatus,jdbcType=INTEGER}");
        }
        
        if (record.getShippingStatus() != null) {
            sql.SET("shipping_status = #{shippingStatus,jdbcType=INTEGER}");
        }
        
        if (record.getPayStatus() != null) {
            sql.SET("pay_status = #{payStatus,jdbcType=INTEGER}");
        }
        
        if (record.getConsignee() != null) {
            sql.SET("consignee = #{consignee,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            sql.SET("country = #{country,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            sql.SET("province = #{province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.SET("city = #{city,jdbcType=VARCHAR}");
        }
        
        if (record.getDistrict() != null) {
            sql.SET("district = #{district,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.SET("mobile = #{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getPostscript() != null) {
            sql.SET("postscript = #{postscript,jdbcType=VARCHAR}");
        }
        
        if (record.getShippingId() != null) {
            sql.SET("shipping_id = #{shippingId,jdbcType=TINYINT}");
        }
        
        if (record.getShippingName() != null) {
            sql.SET("shipping_name = #{shippingName,jdbcType=VARCHAR}");
        }
        
        if (record.getPayId() != null) {
            sql.SET("pay_id = #{payId,jdbcType=VARCHAR}");
        }
        
        if (record.getPayName() != null) {
            sql.SET("pay_name = #{payName,jdbcType=VARCHAR}");
        }
        
        if (record.getShippingFee() != null) {
            sql.SET("shipping_fee = #{shippingFee,jdbcType=DECIMAL}");
        }
        
        if (record.getActualPrice() != null) {
            sql.SET("actual_price = #{actualPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getIntegral() != null) {
            sql.SET("integral = #{integral,jdbcType=INTEGER}");
        }
        
        if (record.getIntegralMoney() != null) {
            sql.SET("integral_money = #{integralMoney,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderPrice() != null) {
            sql.SET("order_price = #{orderPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getGoodsPrice() != null) {
            sql.SET("goods_price = #{goodsPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAddTime() != null) {
            sql.SET("add_time = #{addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getConfirmTime() != null) {
            sql.SET("confirm_time = #{confirmTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPayTime() != null) {
            sql.SET("pay_time = #{payTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFreightPrice() != null) {
            sql.SET("freight_price = #{freightPrice,jdbcType=INTEGER}");
        }
        
        if (record.getCouponId() != null) {
            sql.SET("coupon_id = #{couponId,jdbcType=INTEGER}");
        }
        
        if (record.getParentId() != null) {
            sql.SET("parent_id = #{parentId,jdbcType=INTEGER}");
        }
        
        if (record.getCouponPrice() != null) {
            sql.SET("coupon_price = #{couponPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getCallbackStatus() != null) {
            sql.SET("callback_status = #{callbackStatus,jdbcType=CHAR}");
        }
        
        if (record.getShippingNo() != null) {
            sql.SET("shipping_no = #{shippingNo,jdbcType=VARCHAR}");
        }
        
        if (record.getFullCutPrice() != null) {
            sql.SET("full_cut_price = #{fullCutPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getOrderType() != null) {
            sql.SET("order_type = #{orderType,jdbcType=VARCHAR}");
        }
        
        if (record.getBrandId() != null) {
            sql.SET("brand_id = #{brandId,jdbcType=INTEGER}");
        }
        
        if (record.getSettlementTotalFee() != null) {
            sql.SET("settlement_total_fee = #{settlementTotalFee,jdbcType=INTEGER}");
        }
        
        if (record.getAllPrice() != null) {
            sql.SET("all_price = #{allPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAllOrderId() != null) {
            sql.SET("all_order_id = #{allOrderId,jdbcType=VARCHAR}");
        }
        
        if (record.getPromoterId() != null) {
            sql.SET("promoter_id = #{promoterId,jdbcType=INTEGER}");
        }
        
        if (record.getBrokerage() != null) {
            sql.SET("brokerage = #{brokerage,jdbcType=DECIMAL}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_order
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, OrderCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}