package com.tw.mapper;

import com.tw.model.UserCoupon;
import com.tw.model.UserCouponCriteria.Criteria;
import com.tw.model.UserCouponCriteria.Criterion;
import com.tw.model.UserCouponCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserCouponSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    public String countByExample(UserCouponCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("twshop_user_coupon");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    public String deleteByExample(UserCouponCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("twshop_user_coupon");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    public String insertSelective(UserCoupon record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("twshop_user_coupon");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getCouponId() != null) {
            sql.VALUES("coupon_id", "#{couponId,jdbcType=INTEGER}");
        }
        
        if (record.getCouponNumber() != null) {
            sql.VALUES("coupon_number", "#{couponNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUsedTime() != null) {
            sql.VALUES("used_time", "#{usedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddTime() != null) {
            sql.VALUES("add_time", "#{addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOrderId() != null) {
            sql.VALUES("order_id", "#{orderId,jdbcType=INTEGER}");
        }
        
        if (record.getSourceKey() != null) {
            sql.VALUES("source_key", "#{sourceKey,jdbcType=VARCHAR}");
        }
        
        if (record.getReferrer() != null) {
            sql.VALUES("referrer", "#{referrer,jdbcType=INTEGER}");
        }
        
        if (record.getCouponStatus() != null) {
            sql.VALUES("coupon_status", "#{couponStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCouponPrice() != null) {
            sql.VALUES("coupon_price", "#{couponPrice,jdbcType=DECIMAL}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    public String selectByExample(UserCouponCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("coupon_id");
        sql.SELECT("coupon_number");
        sql.SELECT("user_id");
        sql.SELECT("used_time");
        sql.SELECT("add_time");
        sql.SELECT("order_id");
        sql.SELECT("source_key");
        sql.SELECT("referrer");
        sql.SELECT("coupon_status");
        sql.SELECT("coupon_price");
        sql.FROM("twshop_user_coupon");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserCoupon record = (UserCoupon) parameter.get("record");
        UserCouponCriteria example = (UserCouponCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("twshop_user_coupon");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getCouponId() != null) {
            sql.SET("coupon_id = #{record.couponId,jdbcType=INTEGER}");
        }
        
        if (record.getCouponNumber() != null) {
            sql.SET("coupon_number = #{record.couponNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUsedTime() != null) {
            sql.SET("used_time = #{record.usedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddTime() != null) {
            sql.SET("add_time = #{record.addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{record.orderId,jdbcType=INTEGER}");
        }
        
        if (record.getSourceKey() != null) {
            sql.SET("source_key = #{record.sourceKey,jdbcType=VARCHAR}");
        }
        
        if (record.getReferrer() != null) {
            sql.SET("referrer = #{record.referrer,jdbcType=INTEGER}");
        }
        
        if (record.getCouponStatus() != null) {
            sql.SET("coupon_status = #{record.couponStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCouponPrice() != null) {
            sql.SET("coupon_price = #{record.couponPrice,jdbcType=DECIMAL}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_user_coupon");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("coupon_id = #{record.couponId,jdbcType=INTEGER}");
        sql.SET("coupon_number = #{record.couponNumber,jdbcType=VARCHAR}");
        sql.SET("user_id = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("used_time = #{record.usedTime,jdbcType=TIMESTAMP}");
        sql.SET("add_time = #{record.addTime,jdbcType=TIMESTAMP}");
        sql.SET("order_id = #{record.orderId,jdbcType=INTEGER}");
        sql.SET("source_key = #{record.sourceKey,jdbcType=VARCHAR}");
        sql.SET("referrer = #{record.referrer,jdbcType=INTEGER}");
        sql.SET("coupon_status = #{record.couponStatus,jdbcType=TINYINT}");
        sql.SET("coupon_price = #{record.couponPrice,jdbcType=DECIMAL}");
        
        UserCouponCriteria example = (UserCouponCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UserCoupon record) {
        SQL sql = new SQL();
        sql.UPDATE("twshop_user_coupon");
        
        if (record.getCouponId() != null) {
            sql.SET("coupon_id = #{couponId,jdbcType=INTEGER}");
        }
        
        if (record.getCouponNumber() != null) {
            sql.SET("coupon_number = #{couponNumber,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getUsedTime() != null) {
            sql.SET("used_time = #{usedTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddTime() != null) {
            sql.SET("add_time = #{addTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{orderId,jdbcType=INTEGER}");
        }
        
        if (record.getSourceKey() != null) {
            sql.SET("source_key = #{sourceKey,jdbcType=VARCHAR}");
        }
        
        if (record.getReferrer() != null) {
            sql.SET("referrer = #{referrer,jdbcType=INTEGER}");
        }
        
        if (record.getCouponStatus() != null) {
            sql.SET("coupon_status = #{couponStatus,jdbcType=TINYINT}");
        }
        
        if (record.getCouponPrice() != null) {
            sql.SET("coupon_price = #{couponPrice,jdbcType=DECIMAL}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, UserCouponCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}