package com.tw.mapper;

import com.tw.model.UserCoupon;
import com.tw.model.UserCouponCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserCouponSqlProvider.class, method="countByExample")
    long countByExample(UserCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @DeleteProvider(type=UserCouponSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @Delete({
        "delete from twshop_user_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @Insert({
        "insert into twshop_user_coupon (id, coupon_id, ",
        "coupon_number, user_id, ",
        "used_time, add_time, ",
        "order_id, source_key, ",
        "referrer, coupon_status, ",
        "coupon_price)",
        "values (#{id,jdbcType=INTEGER}, #{couponId,jdbcType=INTEGER}, ",
        "#{couponNumber,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{usedTime,jdbcType=TIMESTAMP}, #{addTime,jdbcType=TIMESTAMP}, ",
        "#{orderId,jdbcType=INTEGER}, #{sourceKey,jdbcType=VARCHAR}, ",
        "#{referrer,jdbcType=INTEGER}, #{couponStatus,jdbcType=TINYINT}, ",
        "#{couponPrice,jdbcType=DECIMAL})"
    })
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @InsertProvider(type=UserCouponSqlProvider.class, method="insertSelective")
    int insertSelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserCouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_number", property="couponNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="used_time", property="usedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="add_time", property="addTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="source_key", property="sourceKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="referrer", property="referrer", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_status", property="couponStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="coupon_price", property="couponPrice", jdbcType=JdbcType.DECIMAL)
    })
    List<UserCoupon> selectByExampleWithRowbounds(UserCouponCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserCouponSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_number", property="couponNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="used_time", property="usedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="add_time", property="addTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="source_key", property="sourceKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="referrer", property="referrer", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_status", property="couponStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="coupon_price", property="couponPrice", jdbcType=JdbcType.DECIMAL)
    })
    List<UserCoupon> selectByExample(UserCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, coupon_id, coupon_number, user_id, used_time, add_time, order_id, source_key, ",
        "referrer, coupon_status, coupon_price",
        "from twshop_user_coupon",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="coupon_id", property="couponId", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_number", property="couponNumber", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="used_time", property="usedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="add_time", property="addTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="source_key", property="sourceKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="referrer", property="referrer", jdbcType=JdbcType.INTEGER),
        @Result(column="coupon_status", property="couponStatus", jdbcType=JdbcType.TINYINT),
        @Result(column="coupon_price", property="couponPrice", jdbcType=JdbcType.DECIMAL)
    })
    UserCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserCouponSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserCoupon record, @Param("example") UserCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserCouponSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserCoupon record, @Param("example") UserCouponCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserCouponSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table twshop_user_coupon
     *
     * @mbg.generated
     */
    @Update({
        "update twshop_user_coupon",
        "set coupon_id = #{couponId,jdbcType=INTEGER},",
          "coupon_number = #{couponNumber,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=VARCHAR},",
          "used_time = #{usedTime,jdbcType=TIMESTAMP},",
          "add_time = #{addTime,jdbcType=TIMESTAMP},",
          "order_id = #{orderId,jdbcType=INTEGER},",
          "source_key = #{sourceKey,jdbcType=VARCHAR},",
          "referrer = #{referrer,jdbcType=INTEGER},",
          "coupon_status = #{couponStatus,jdbcType=TINYINT},",
          "coupon_price = #{couponPrice,jdbcType=DECIMAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserCoupon record);
}